### ISSUE TITLE
ゲームが始まる前

### ISSUE THREAD

**Issue by hirotada-t** [Recursion-Group-P/Memo#2]
ゲーム開始前にロビーで行う設定項目についてまとめます。

### ゲームの参加人数

* プレイヤー or NPCの人数を選択する
* プレイヤーは二人 or 四人のみ
* プレイヤー人数によってNPCの選択肢を変更

### 思考時間

* 5分/10分/20分

### 開始位置

* 角/中央/どこでも

## その他（オンライン実装時・優先度が低い・なくても良い）

* アカウント作成
* ゲストアカウント作成
* 質問・感想フォーラム（掲示板）
* チャット
* オンラインユーザーの表示
* 問い合わせ・寄付
* BGM・SE
* プロフ
* 他人の部屋に参加する
* 他人のゲームを観戦する
* ランダムマッチング機能
* IDで指定したユーザーと対戦機能

**Comment by tkwonn** [comment]
すごくいいと思います！

FAQsページを作るのはどうでしょう？
例えば、
Q. Blokeeのルールがいまいちわかりません。
A. Blokeeは〜
みたいなよくある質問などをこちら側で準備しておくようなものです。

オンラインは今回やらないです。
プレイヤー２人の場合→14 * 14 = 196
プレイヤー４人の場合→20 * 20 = 400

**Comment by hayato0309** [comment]
@hirotada-t 
ありがとうございます！
「その他」より上の部分を実際のゲームと比較しましたが、網羅できてて良いと思います！
ワイヤーフレーム作成時に取り込んでいきます！

@tkwonn 
FAQsページいいですね！
僕たちも最初ルールさっぱりだったので、ユーザーのことを考慮すると、あるとベターかなと思います。
このページをそのまま参考にできそうですね！
https://blokee.mattle.online/lobby/forum/topic/Z2bJJGnhgLqLRxKMm/blokus-game-rules
