### ISSUE TITLE
ゲームの開始

### ISSUE THREAD

**Issue by hirotada-t** [Recursion-Group-P/Memo#3]
### ターンの切り替わりをユーザがどのようにして気づくか

見本だと自分のターンに変わったことが分かりにくいので、改善案を考えたいです。

改善案）
* ターンプレイヤーにリマインダーを表示する
* ターンの切り替わりでSEやアニメーションを使う
* 自分の配置済みピースが点滅（未配置のピースをクリックで点滅を止める）

### ターンが切り替わる前にシステムが確認しておくことはないか

* 自分のタイマーオフ
* 次のユーザーが誰か
* 次のユーザーのタイマーオン
* 置き場所の有無を確認（無ければ自動的にパス）

### 何を持ってエラーがないと判断するか

* （初手のみ）指定した場所に角を置いていること
* 自分のピースの角に置いていること
* 自分のピースの辺に触れていないこと
* 相手のピースと被さっていないこと

### プレイヤーAのターンでできる動作は何か

* ピースを選択/キャンセル
* 右回転
* 左回転
* フリップ
* 置き場所を選択
* 置く/キャンセル
* 置き場所を選択<-->回転・フリップは、同一画面でシームレスに実行可能
* パス

### プレイヤーの違法な選択はどのようにユーザに伝えるか（ポップアップ画面で伝える？それともシステム自体がそれを許容しないようにする？）

置き場所を表示するサポートありなら、システムで許容せず、違法な選択ができないようにするのが良いと思います。
サポートなしでアラートをつけるのもありな気がします。
もしくは、ゲーム開始前の設定項目でサポートの有無を追加するなども？

**Comment by hirotada-t** [comment]
パスを選択時の挙動について、見本ではパス＝負けを認めることになっています。
この仕様はどうしましょうか？？

考えてみると、置き場がなくてパスするなら、負けを認めることと同じですね。
「パス」ではなく「コンシード」という表現が良いかもしれません。

システムで置き場所があるかどうか判断するなら、ボタンを無くすのもあり？

**Comment by tkwonn** [comment]
```
ターンが切り替わる前にシステムが確認しておくことはないか
自分のタイマーオフ
次のユーザーが誰か
次のユーザーのタイマーオン
置き場所の有無を確認（無ければ自動的にパス）
```

システムが置き場所の有無を確認という処理が難しい場合、自動的にパスするのではなく、ユーザにどのピースも置くことができないことを自発的に感じさせてパスボタンを押させるでもありな気がします。後々ゲーム自体が完成して追加できそうな部分でもあるので。

```
プレイヤーAのターンでできる動作は何か
ピースを選択/キャンセル
右回転
左回転
フリップ
置き場所を選択
置く/キャンセル
置き場所を選択<-->回転・フリップは、同一画面でシームレスに実行可能
パス
```

置く・キャンセルの部分ですが、これはルール上一度おいたピースを変更できないように設定することで、省くことができますが、ダイアログみたいなのでOKかCancelかユーザに確認するのもありですね。

**Comment by hayato0309** [comment]
> ターンの切り替わりをユーザがどのようにして気づくか

自分のターンであることに気づきにくいのは同意ですw

１）　「あなたのターンです」みたいなモーダルが出てくる
２）　画面をクリックするとモーダルが消えて、ブロック選択ができるようになる
みたいな感じでいいのではと思いました。（hirotadaさんの第一案ですかね）

>ターンが切り替わる前にシステムが確認しておくことはないか

「（無ければ自動的にパス）」の部分ですが、
kwonさんと同意見で、ユーザーに一回考えさせて自発的にパスをクリックしてもらう、がゲーム的に面白いかと思いました！

> 何を持ってエラーがないと判断するか

こちらは書いていただいているもので問題ないと思います。
ありがとうございます！

>プレイヤーAのターンでできる動作は何か

置く・キャンセルの部分ですが、kwonさんのアイデア（ルール上で置いたピースは変更できないようにする）のがいいと思いました。
このアイデアでいくとすると、置く前に「ここでいいですか？」と確認するのがベターですね！

>プレイヤーの違法な選択はどのようにユーザに伝えるか（ポップアップ画面で伝える？それともシステム自体がそれを許容しないようにする？）

「ゲーム開始前の設定項目でサポートの有無を追加する」がいいと思いました！

**Comment by hayato0309** [comment]
@tkwonn @hirotada-t @hiroto0222 
見本ゲームのFORUMページ（リンクは以下）で興味深いコメントを見つけました。
https://blokee.mattle.online/lobby/forum/topic/Z2bJJGnhgLqLRxKMm/blokus-game-rules

▼コメント
https://gyazo.com/705524bba3e9fccae90ed927de614941
この問題どうにかしたいですよね😅

▼解決策案
１）20秒おきにユーザーが離脱していないか確認するモーダルを表示
　　・そのプレイヤーのターンになってから20秒経過すると、離脱をしていないか確認するモーダルを表示。
　　・そのモーダル上のボタンを10秒以内にクリックすることでゲームを継続できる。
　　・もし10秒以内にボタンをクリックしなかったら、そのプレーヤーは離脱したものとみなし、そのターンはスキップされ、それ以降もターンは回ってこない。

こんな感じでいかがでしょうか？

**Comment by tkwonn** [comment]
なるほど、これも候補として持っておきましょう！
ただ実装する際は優先度低くていいかもですね（テスト時に毎回ポップアップが出てきたら困るので。）

**Comment by hirotada-t** [comment]
> @tkwonn @hirotada-t @hiroto0222 見本ゲームのFORUMページ（リンクは以下）で興味深いコメントを見つけました。 https://blokee.mattle.online/lobby/forum/topic/Z2bJJGnhgLqLRxKMm/blokus-game-rules
> 
> ▼コメント https://gyazo.com/705524bba3e9fccae90ed927de614941 この問題どうにかしたいですよね😅
> 
> ▼解決策案 １）20秒おきにユーザーが離脱していないか確認するモーダルを表示 　　・そのプレイヤーのターンになってから20秒経過すると、離脱をしていないか確認するモーダルを表示。 　　・そのモーダル上のボタンを10秒以内にクリックすることでゲームを継続できる。 　　・もし10秒以内にボタンをクリックしなかったら、そのプレーヤーは離脱したものとみなし、そのターンはスキップされ、それ以降もターンは回ってこない。
> 
> こんな感じでいかがでしょうか？

**Comment by hirotada-t** [comment]
> ▼解決策案 １）20秒おきにユーザーが離脱していないか確認するモーダルを表示 　　・そのプレイヤーのターンになってから20秒経過すると、離脱をしていないか確認するモーダルを表示。 　　・そのモーダル上のボタンを10秒以内にクリックすることでゲームを継続できる。 　　・もし10秒以内にボタンをクリックしなかったら、そのプレーヤーは離脱したものとみなし、そのターンはスキップされ、それ以降もターンは回ってこない。

こちらの解決案で良いと思います。
追加機能として、基本機能が完成した後に実装していきましょう！
