### ISSUE TITLE
ゲームの終了時

### ISSUE THREAD

**Issue by hirotada-t** [Recursion-Group-P/Memo#4]
## 誰が勝ち、誰が負けたかどう表示するか

表示上では置いたピースのポイントの合計値が分かりやすいと思います。
（システム内では残ったピースで順位を判別したほうが組みやすい？）
あとは順番のアイコンをつけることですね。

順位が被った時の処理はどうしましょうか。
同率順位（例：1-2-2-4/1-2-3-3/など）で良いかもしれませんが、他にアイディアがあれば検討しましょう！

## その他、もう一度プレイするかゲームを退出するかなどのオプションを表示するか

オフラインモードなら、もう一度プレイする場合は、開始前に使った部屋を作る時に使ったプログラムが使えそうです。

オンラインでの実装時には、ゲームの申込み機能が必要ですね（IDを指定して申し込むのような）。

**Comment by tkwonn** [comment]
いいと思います！
順位が被ったときは同率順位で大丈夫かと思います。

```
オフラインモードなら、もう一度プレイする場合は、開始前に使った部屋を作る時に使ったプログラムが使えそうです。
```
そうですね！設定そのままでもう一度やるか、設定変えてやるか、ホームページに戻るかという選択肢がありますね。
まぁ順位だけ示して、あとはユーザにもう一度プレイして欲しい場合はNavbarのリンクをたどってもらうとかでもいい気がするので、優先度的にはこの実装は低くなりますね。

**Comment by hayato0309** [comment]
置いたピースの合計値が同じだった場合は、残り時間で判定してはいかがでしょうか？
残り時間も同じだった場合は、同率でいいと思います！

**Comment by tkwonn** [comment]
確かにそれもありですね！

**Comment by hirotada-t** [comment]
残り時間という手がありましたね。
順位付けはそれで良いと思います。

**Comment by tkwonn** [comment]
とりあえず現段階でのまとめを以下のREADMEに書いておきました。
https://github.com/Recursion-Group-P/Memo/blob/main/Requirements.md

まだ少し要件定義や勝利判定、CPUアルゴリズムの部分で理解できていない部分が多いかと思うので、ある程度先に見た目や簡単な機能を実装していって逐次何か発見があったらまとめるようにします。

反応スタンプが３つ揃ったらクローズしますので、ご協力お願いします！

**Comment by hayato0309** [comment]
@tkwonn 
まとめありがとうございます！

「プレイヤーAのターンでできる動作は何か」の「置く/キャンセル」って結局どうするんでしたっけ？🤔
キャンセルできるようにするか、ルールで禁止してしまうかというディスカッションがIssue#3『ゲームの開始』にありました！

僕はルールでキャンセルできないようにしてしまっていいのでは？と思っています！

**Comment by hirotada-t** [comment]
一度置いたものはキャンセルできなくて良いと思いますが、見本だと置くのを決定するまでに
・ピースの選択
・置き場所の選択
・置くかどうか最終確認
の3段階ありますね。

最終確認まではキャンセルボタンがついて、それぞれの状態を行き来できるようになっています。

**Comment by hayato0309** [comment]
@hirotada-t 
てっきり置いた後のキャンセルだと思ってました😅
今認識クリアになりました。
「置く/キャンセル」問題なしです！
ありがとうございます！

**Comment by tkwonn** [comment]
クローズします！
