### ISSUE TITLE
ブロックの命名規則

### ISSUE THREAD

**Issue by hirotada-t** [Recursion-Group-P/Memo#5]
![piece](https://user-images.githubusercontent.com/68522105/168458011-d907b9bb-1a6f-475e-a608-67e4d80dc6c5.png)

ブロックごとの呼び方を統一しておいた方が、後々コミュニケーションを取る上で楽かもしれません。

上から順番に何かいい案があれば教えてください。
例えば直線のブロックだと長さによって　i1, i2, i3,....
T型はそのままTとか、一番下の段の左はXとか...
回転したりフリップしてあるだけの型は一つの名前だけ決めれば大丈夫そうですが

https://github.com/Recursion-Group-P/Memo/pull/1#issuecomment-112664297

**Comment by hirotada-t** [comment]
こんな感じはどうでしょう。

1. i1
2. i2
3. i3
4. L3
5. i4
6. J4
7. Square
8. z4
9. T4
10. c
11. w
12. i5
13. J5
14. T5
15. L5
16. x
17. k5
18. z5
19. z5wide
20. i1square
21. T5wide

**Comment by tkwonn** [comment]
@hirotada-t ありがとうございます！

直線のブロックは四角形の個数で、i1, i2, i3, i4, i5で決まりですね！
その他にわかりやすい形としてT, X, C, Wがありますね。

L3 = V
i1Square = P
T5wide = Y

にするのはどうでしょう？

**Comment by hayato0309** [comment]
皆さんありがとうございます！

4. L3をVにすると、15. L5もV系になりそうですね🤔

直角に曲がっている、かつ腕(?)の長さが等しいものをVにするのはいかがでしょう？
この場合、
・4番：V3 
・15番：V5
になります！

**Comment by hirotada-t** [comment]
意見ありがとうございます！
現状をまとめると下記になります↓

1. i1
2. i2
3. i3
4. v3
5. i4
6. J4
7. Square
8. z4
9. T4
10. c
11. w
12. i5
13. J5
14. T5
15. v5
16. x
17. k5
18. z5
19. z5wide
20. p
21. y
