### ISSUE TITLE
技術スタック

### ISSUE THREAD

**Issue by tkwonn** [Recursion-Group-P/Memo#6]
Level２
Desktop or Mobile App推奨（Vue2 + Quasar framework v1)
＋
Login + Replay (Firebase Web version 8 or 9)

でいこうかと考えていますが、どうでしょうか？

**Comment by hirotada-t** [comment]
Firebaseについては、9で良いかなと思っています！
以前それを使ってプログラムを組んだことがありますが、8より気持ち分かりやすく使える印象です。

FWについては別issueにコメントしました。

**Comment by hayato0309** [comment]
@tkwonn 
ご確認ありがとうございます！

1点だけ確認させていただきたいです。
「Desktop or Mobile App推奨」の部分は、Webアプリに変更するって先週の土曜にみんなでお話しした記憶があるのですが、あってますか？😅

この部分以外は問題ないと思います。
よろしくお願いします！

**Comment by tkwonn** [comment]
なるほど！自分は逆に8しか使ったことないですw(むかし)
9の方が容量の負担も少ないらしいですし、とりあえず9でいきましょう。

**Comment by hiroto0222** [comment]
最初は Web アプリとして開発を進め、時間次第マルチプラットフォームにするという形だと思います。
Desktop アプリの場合 Web アプリ から Quasar/Electron を使ってデプロイが簡単に実装出来そうですが、Mobile アプリの場合 UI にかなり時間が掛かかりそうです😅

**Comment by hayato0309** [comment]
皆さんFirebaseを使ったことがある中恥ずかしいのですが、僕はFirebase触ったこともないので選定は皆さんにお任せいたします。
Vue2 + Quasar framework v1の部分は、こちらで問題ないです！

**Comment by tkwonn** [comment]
クローズします！
